### ISSUE TITLE
Show Active module 

### ISSUE THREAD

**Issue by anisharaz** [anisharaz/resourcesite#27]
## current design doesnot show which module is opened currently, mark the module link active for which the module is opened

![image](https://github.com/anisharaz/resourcesite/assets/105302254/36e26ea7-9f1f-4a25-b7e9-25f0abcda173)

**Comment by nawinsharma** [comment]
working

**Comment by nawinsharma** [comment]
[Screencast from 2024-05-23 01-16-03.webm](https://github.com/anisharaz/resourcesite/assets/126372969/c536c421-d094-4ddc-bba7-f296807c6dd9)
Hey @anisharaz , Do you want more specific? or is this ok?

**Comment by anisharaz** [comment]
Thats beautiful , works 🙌
