### ISSUE TITLE
Better colour pallete

### ISSUE THREAD

**Issue by anisharaz** [anisharaz/resourcesite#3]
The current colour palette is a little dark and unmatching , need a proper colour schema.

**Comment by thinley4** [comment]
Light Mode

Text - #0F0A30
Background - #FFFFFF
Primary - #2f27ce
Secondary - #a19ed2
Accent - #403d94

Dark Mode

Text - #ffffff
Background - #020426
Primary - #3730bd
Secondary - #221d74
Accent - #47459d

**Comment by thinley4** [comment]
Looks pretty good 
let me know your opinion.

**Comment by anisharaz** [comment]
Screenshots of the pages in both the mode will give a better idea of how it looks !

**Comment by thinley4** [comment]
Light Mode

![Screenshot Capture - 2024-06-03 - 14-51-26](https://github.com/anisharaz/resourcesite/assets/128626751/73913ce4-2675-4e27-9d24-af26f5b6df85)

Dark Mode

![Screenshot Capture - 2024-06-03 - 14-53-54](https://github.com/anisharaz/resourcesite/assets/128626751/e92abab7-38ef-4273-9496-a0523b1a33d6)

**Comment by anisharaz** [comment]
The secondary color should be a bright and attractive type of colour so that we can use the colour in any component of website that we want to be noticeable to the viewer. Currently all three colours are shades of same blue colour


https://youtu.be/KMS3VwGh3HY?si=O9sQ7iQahlTk032N

https://youtu.be/UWwNIMHFdW4?si=x-m3wn05k5hw5BAa

https://youtu.be/eXcKOqviLE0?si=DQaKHyIVRQ4wp3bN

**Comment by anisharaz** [comment]
To start off its cool 🎇 @thinley4
