### ISSUE TITLE
Module View Desktop design

### ISSUE THREAD

**Issue by anisharaz** [anisharaz/resourcesite#4]
the page which shows the PDF to read needs to have a left navigation section where extra pdfs or study resources, along with module pdf, can be viewed.
something like this.
![image](https://github.com/anisharaz/resourcesite/assets/105302254/7f366a44-93df-4383-ad56-b7f79379bd0b)

**Comment by thinley4** [comment]
Working on prettifying.

**Comment by anisharaz** [comment]
go ahead...
